### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xxzefgh** [brunjick/bog-cli#1]
### TODO:
- [ ] Add `accounts` command
- [ ] Add `loans` command
- [ ] Add `deposits` command
- [ ] Add `currencies` command
